// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string;
  arrow: string;
  hidden: string;
  link: string;
  links: string;
  navigation: string;
  toggle: string;
}
export const cssExports: CssExports;
export default cssExports;
