// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  loader: string;
  'loader-1': string;
  'loader-2': string;
  'loader-3': string;
  loaderContainer: string;
  span: string;
}
export const cssExports: CssExports;
export default cssExports;
