// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'dash': string;
  'fundo': string;
  'left-sparks': string;
  'leftSparks': string;
  'olhos': string;
  'paoBaixo': string;
  'paoCima': string;
  'path': string;
  'rightSparks': string;
  'rotatepao': string;
  'scales': string;
}
export const cssExports: CssExports;
export default cssExports;
